[project]
name = "sscout"
version = "0.0.1"
packages = ["plugins", "sscout"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project.scripts]
sscout = "sscout.sscout.__main__:main"
