[project]
name = "sscout"
version = "0.0.1"

[tool.setuptools]
package = ["plugins", "sscout"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
sscout = "sscout.sscout.__main__:main"
